name: Output event details
on: issues
jobs:
  print-event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: echo "Event details ${{ toJson(github.event) }}"
