name: Push flow
on:
  pull_request:
    types: opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: echo "Event details ${{ toJson(github.event) }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
